// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0

package repository

import (
	"encoding/json"
)

type Order struct {
	ID       int64           `json:"id"`
	OrderUid string          `json:"order_uid"`
	Data     json.RawMessage `json:"data"`
}
