// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0
// source: queries.sql

package repository

import (
	"context"
	"encoding/json"
)

const createOrder = `-- name: CreateOrder :exec
INSERT INTO orders(
    data
) VALUES (
    $1
)
`

func (q *Queries) CreateOrder(ctx context.Context, data json.RawMessage) error {
	_, err := q.db.ExecContext(ctx, createOrder, data)
	return err
}

const getOrderByID = `-- name: GetOrderByID :one
SELECT data 
FROM orders
WHERE data ->> 'order_uid' = $1
`

func (q *Queries) GetOrderByID(ctx context.Context, data json.RawMessage) (json.RawMessage, error) {
	row := q.db.QueryRowContext(ctx, getOrderByID, data)
	err := row.Scan(&data)
	return data, err
}
