// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0

package repository

import (
	"context"
	"encoding/json"
)

type Querier interface {
	CreateOrder(ctx context.Context, data json.RawMessage) error
	GetOrderByID(ctx context.Context, data json.RawMessage) (json.RawMessage, error)
}

var _ Querier = (*Queries)(nil)
